### ISSUE TITLE
Low GPU utilization

### ISSUE THREAD

**Issue by JonWofr** [MingSun-Tse/Collaborative-Distillation#18]
Hi,
first of all thank you guys so much for your work, i really love it! :)

I compared the performance of this algorithm with the default wct-tf algorithm and I noticed that it takes roughly twice the time for the algorithm to run on one image than it does for the wct-tf (with same settings applied). 
I read your paper and saw that in practice it should rather be faster than slower so I inspected  my GPU utilization and found out that it was not nearly fully utilized. Here is a screenshot of MSI afterburner whilst running the style transfer.

![image](https://user-images.githubusercontent.com/49523842/107884865-7858e000-6ef7-11eb-9dd2-a26a2d901aed.png)

As for other information, I used following command to start the stylization process.

![image](https://user-images.githubusercontent.com/49523842/107884920-a9391500-6ef7-11eb-848a-2d67854f236f.png)

And my PC has following specs:
CPU: AMD Ryzen 3600x 
GPU: Nvidea Geforce GTX 1080
OS: Win10

So first thing that came to my mind when I saw that the GPU was not fully utilized was that the CPU would be the bottleneck. In Tensorflow I encountered the problem of the CPU being the bottleneck before. The reason for that was that data augmentation did only run single-core. Therefore I checked whether or not this would also be the case in Pytorch. But the afterburner charts show that the other cores are also used and CPU load is only at around 50% across all 12 cores. 

So I am wondering if this might come down to me using Windows and not Linux or if there might be something else I am missing out.

I would be really thankful for any advice.

Cheers Jonas

**Comment by MingSun-Tse** [comment]
Hi @JonWofr , thanks a lot for your interest in our work! so you find the GPU utility is low (if I understand your question correctly) -- I think it is because the svd operation in WCT is on CPU. When CPUs are doing svd, the GPU will be idle. To make it faster, trying to speedup the svd operation is a good idea. 

As for wct-pytorch is 2x slower than wct-tf. I would say it is possible considering they are the different DL frameworks (as for detailed implementation reason, I don't know either). 

Let me know if you have further questions.
