### ISSUE TITLE
Is there any way to preserve the color of the content image?

### ISSUE THREAD

**Issue by suoych** [MingSun-Tse/Collaborative-Distillation#21]
Hello, thanks for sharing the brilliant work. I just have a question that is there any way to restore the color of the content image? In the essay "Arbitrary Style Transfer in Real-time with Adaptive Instance Normalization" [Huang+, ICCV2017]. They provided a way keep the original color. I don't know if it is poosible for this project to do that. 
![image](https://user-images.githubusercontent.com/29878050/127332405-0faf8397-1418-4af1-944a-52f8e4dec960.png)

**Comment by MingSun-Tse** [comment]
Hi @suoych , thanks for your interest in our work! We did not have that experiment in our paper so I cannot tell you it definitely can, but methodologically, I think the compressed model can achieve so. Because this work is for model compression. _It does not change the stylization pipeline of WCT or AdaIN_. If AdaIN already provides a way to keep the content color, the compressed model should also be able to do so (though it might not be as qualitative due to smaller model size) . You may try it out yourself if you are interested. Let me know if you have any problems!

**Comment by suoych** [comment]
> Hi @suoych , thanks for your interest in our work! We did not have that experiment in our paper so I cannot tell you it definitely can, but methodologically, I think the compressed model can achieve so. Because this work is for model compression. _It does not change the stylization pipeline of WCT or AdaIN_. If AdaIN already provides a way to keep the content color, the compressed model should also be able to do so (though it might not be as qualitative due to smaller model size) . You may try it out yourself if you are interested. Let me know if you have any problems!

Thanks for your reply, I'll try it.
